name: x_express
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  http: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_staggered_animations:
  intl:
  cached_network_image: ^3.2.3
  timeago: ^3.4.0
  photo_view: ^0.14.0
  shimmer: ^3.0.0
  fluttertoast: ^8.2.1
  lazy_load_scrollview:
  flutter_svg:
  lottie: ^3.3.1
  dio: ^5.0.2
  currency_text_input_formatter: ^2.2.2
  permission_handler: ^11.3.1
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  flutter_lints: ^3.0.2
  change_app_package_name: ^1.1.0
  carousel_slider: ^5.0.0
  onesignal_flutter:
  device_preview: ^1.2.0
  share_plus: ^7.2.2
  flutter_html:

  file_picker: ^8.3.1
  #  pull_to_refresh: ^2.0.0

  font_awesome_flutter: ^10.8.0
  flutter_dotenv: ^5.1.0
  uuid:
  webview_flutter: ^2.0.0
  pinput: ^5.0.0
  flutter_inappwebview: ^6.1.5
  syncfusion_flutter_pdfviewer:
  syncfusion_flutter_core:
  dotted_line: ^3.2.3
  in_app_update:
  google_fonts:
  flutter_widget_from_html:
  flutter_launcher_icons:
  phone_form_field:
  intl_phone_field:
  pin_code_fields:
  syncfusion_flutter_datepicker:



#  flutter pub get && flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/beginner.png"





#flutter pub run change_app_package_name:main com.beginnerco.cargo
# com.dottech.kalcargo
# com.kardo.futian
#com.banagroup.cargo
#com.shkarco.cargo


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/
    - assets/mock_orders.json
    - .env



  fonts:
    - family: sf_bold
      fonts:
        - asset: assets/fonts/sf_reg.ttf
    - family: sf_med
      fonts:
        - asset: assets/fonts/sf_reg.ttf

    - family: sf_reg
      fonts:
        - asset: assets/fonts/sf_reg.ttf

